- name: APACHE STOP for 서울시
  hosts: group02
  serial: 1
  gather_facts: false
  # become: true 

  tasks:
    - name: BLOCK - APACHE 중지 실행
      block:
        - name: Apache 중지 스크립트 직접 실행
          ansible.builtin.shell:
            cmd: "{{ apps_dir }}/bin/apache_stop.sh"
          register: apache_stop_result

        - name: Apache stop 결과 출력
          ansible.builtin.debug:
            msg:
              - "호스트 명 = {{ inventory_hostname }}"
              - "결과 코드(RC) = {{ apache_stop_result.rc }}"
              - "스크립트 출력 = "
              - "{{ apache_stop_result.stdout_lines }}"
              
      when: target_groups is search('group02')
      any_errors_fatal: true
